export const projectsData = [
    {
        name: 'Brimo',
        description: 'BRImo is a mobile banking app from Bank BRI, trusted by over 35 million users in Indonesia. It offers a seamless digital banking experience, enabling users to register and open accounts fully online—even from abroad using international phone numbers. BRImo supports international transfers to 160+ countries and QR payments overseas, such as in Singapore. The app also covers lifestyle needs, from game vouchers and streaming to travel bookings and Liga 1 tickets. Users can manage investments like pensions, gold, and stocks directly within the app. Daily transactions such as bill payments, e-wallet top-ups, and QRIS payments are simplified, with added benefits like real-time cashback and BRIpoin rewards. BRImo also offers 24/7 customer service via free call and in-app chat for a complete and convenient banking solution.',
        thumbnail: 'https://virtualexpo.uptpkk.unp.ac.id/shop/public/uploads/all/WAoivwHOXm6h6s8cpIBWrAocTaL4JB8jsfnR7lTl.png',
        tags: [
            'Kotlin',
            'Compose',
            'Hilt',
            'Coroutines',
            'Retrofit',
            'MVVM'
        ],
        type: 'Banking',
        playstore: 'https://play.google.com/store/apps/details?id=id.co.bri.brimo&hl=en',
        appstore: 'https://apps.apple.com/id/app/brimo-bri/id1439730817',
        github: '',
        gallery: [
            'https://play-lh.googleusercontent.com/tERifK6a5054wUAxlaBoSV3xyQ_Cay9EAYHXh0627erVriV-fs0f_Kpeau6-24rlSA=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/zhf_FlUQmkz_7GR7nsLuXe6Hghm4k0AQ0vgdQEDODav_0QWUagW8_XulsuyrikriJhsY=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/Q4aS0NL0D-ME5hd1ql2zw8cNSklXNSepyJkMOF-ERQeU_V2qght4vWJ8oaUTyxVG09A=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/aPZcZNkTCuFA8Dy_iuAtBVRqKjoC9F2XIPMIemJGJRt81Yqon6NHR7XKgAPnd04_MQ=w5120-h2880-rw'
        ],
    },
    {
        name: 'Brimola',
        description: 'BRIMOLA is a mobile application designed for ordering 3kg Pertamina Elpiji gas from distributors (Pangkalan) to agents in a fast, easy, and efficient manner. It offers several key advantages for distributors, including real-time access to Elpiji quota information, a simple and convenient online ordering process, and reduced risk of errors during order entry. With BRIMOLA, gas ordering becomes more accurate and streamlined, helping distributors manage their supply more effectively.',
        thumbnail: 'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/f9/70/78/f9707823-0565-6d8e-6a4f-eb6915f7fca6/AppIcon-0-0-1x_U007emarketing-0-8-0-0-85-220.png/460x0w.webp',
        tags: [
            'Kotlin, Swift',
            'Ktor',
            'Koin',
            'Coroutines',
            'Jetpack',
            'SwiftUI / UIKit',
            'Alamofire',
            'Viper',
            'MVVM'
        ],
        type: 'Order Gas',
        playstore: 'https://play.google.com/store/apps/details?id=id.co.bri.brimola&pcampaignid=web_share',
        appstore: 'https://apps.apple.com/id/app/brimola/id1462786205',
        github: '',
        gallery: [
            'https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/2b/b2/23/2bb22369-edf4-6c6f-1525-fc53eb08237d/0a625c34-831c-405c-b91d-88de8cd23b1b_Home_-_iPhone_6.5_U0022.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/38/63/ea/3863ea39-cfad-a4d9-94c6-b93987ab64d6/fa355e1b-d231-4bc6-b34b-ad4daf849103_Simulator_Screen_Shot_-_iPhone_14_Plus_-_2023-03-15_at_16.19.24.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource126/v4/1c/7a/75/1c7a75d5-93f7-6256-cdef-ceec1b9656b3/ceb1990c-5f0b-4d95-bd99-73cbf2e69358_Order_-_iPhone_6.5_U0022.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/7c/ba/bb/7cbabb81-3b5b-bd71-7cb4-d05af2b03ca5/43ab613f-d69a-4caa-a21a-44781a244e9a_Kalender_-_iPhone_6.5_U0022.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/16/76/ea/1676eae1-7460-e085-4053-627085446db9/a51424e6-4259-42cc-88bf-4f99612f298b_Simulator_Screen_Shot_-_iPhone_12_Pro_Max_-_2021-12-21_at_16.35.21.png/460x0w.webp'
        ],
    },
    {
        name: 'Smart Billing',
        description: 'BRI Smart Billing is an integrated billing management application designed to help businesses and billers manage their invoices and receivables more efficiently, affordably, and quickly. The app provides several key features to streamline the billing process. The Billing feature allows customers to view a list of their outstanding invoices, while the Billing Details feature gives them a detailed view of each bill. Users can also send invoice details via email using the Send Billing Email function. The History feature enables customers to view their payment history, and with the Filter option, they can display paid invoices within a specific date range. Additionally, the Send History Email feature allows users to share payment confirmations via email. Lastly, the Profile section provides access to customer information and the list of registered billers.',
        thumbnail: 'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/d0/84/91/d08491f8-3fdf-7c27-acb0-d98b7df0e3f2/AppIcon-0-0-1x_U007emarketing-0-7-0-sRGB-85-220.jpeg/460x0w.webp',
        tags: [
            'Flutter',
            'Dio',
            'Riverpod',
            'Hive',
            'Flutter Secure Storage',
            'Get It'
        ],
        type: 'Billing Solution',
        playstore: 'https://play.google.com/store/apps/details?id=id.co.bri.billing&pcampaignid=web_share',
        appstore: 'https://apps.apple.com/us/app/bri-smart-billing/id1475608694',
        github: '',
        gallery: [
            'https://is1-ssl.mzstatic.com/image/thumb/Purple112/v4/a7/f8/f5/a7f8f5ae-ef41-1506-3bd3-690617801abb/pr_source.jpg/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple122/v4/10/c5/d3/10c5d392-c59c-e3ea-19c7-4deab185d214/pr_source.jpg/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource112/v4/4e/71/14/4e7114c3-bb7e-f45d-7427-34d67012dfc9/e7f7ea84-397e-45fc-ac34-8c99deb4928c_Rincian_Tagihan_-_iPhone_6.5_U0022.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple112/v4/88/43/c8/8843c83c-00e1-e568-8229-5db3fd0fc5b9/6948f275-615f-42b6-8707-4ed0c2f56d68_Metode_Pembayaran_-_6.5_U0022.png/460x0w.webp'
        ],
    },
    {
        name: 'Junio Smart',
        description: 'Junio Smart is a comprehensive school management application designed to streamline academic, administrative, and communication processes. The platform is web-based for school administrators and teachers, enabling efficient management of academic activities, student data, fee notifications, exam schedules, attendance tracking, and student progress reports. For students and parents, Junio Smart offers a mobile app that provides easy access to class schedules, assignments, school events, attendance records, academic performance, and tuition payment information—all in one integrated and user-friendly platform.',
        thumbnail: 'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/d7/b4/50/d7b45099-408c-d823-8acc-64579f3acfd9/AppIcon-0-0-1x_U007emarketing-0-7-0-0-85-220.png/460x0w.webp',
        tags: [
            'Kotlin, Java, Swift',
            'Hilt',
            'Coroutines',
            'Retrofit',
            'MVVM',
            'Alamofire',
            'SwiftUI'
        ],
        type: 'Education',
        playstore: 'https://play.google.com/store/apps/details?id=id.co.bri.juniosmart&hl=en',
        appstore: 'https://apps.apple.com/us/app/junio-smart/id1462268358',
        github: '',
        gallery: [
            'https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/ca/f5/bf/caf5bfea-3635-84a2-0ceb-cda449216364/tns.knjgvwlk.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/20/c9/1b/20c91b70-5718-71dc-717e-b1647a98fc55/d77b22d7-5197-449c-b6cd-183085ee480b_Simulator_Screen_Shot_-_iPhone_14_Plus_-_2023-09-01_at_09.00.20.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/ab/17/79/ab1779df-c1dc-db6e-7303-b60212e97a57/tns.ekfivqzv.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/a9/64/2e/a9642ebb-8873-d8fd-df78-da61582cc599/tns.iiintqru.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/41/ca/27/41ca2767-fc15-9801-be3a-d88c58cc7783/tns.egtenxzp.png/460x0w.webp',
        ],
    },
    {
        name: 'Bristore',
        description: 'BRIstore is a Supply Chain Platform designed to streamline trade ecosystems by enabling seamless online transactions and inventory management. It allows distributors and retailers to conduct business remotely without face-to-face interactions, offering convenience through real-time product availability, online ordering, and cashless payments—eliminating the need for in-person visits from sales representatives. Key features include User Management for handling distributor and retailer data, Product Management for updating item descriptions, pricing, and stock levels, and Order Management with real-time notifications, billing, and payment confirmations. Additionally, the platform provides comprehensive Financial Reports, allowing distributors to monitor sales, receivables, and inventory, while retailers gain insights into purchases, payables, sales, and stock—enhancing efficiency and reducing marketing costs.',
        thumbnail: 'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/bd/ad/57/bdad57da-412b-300b-2cef-b3778c857845/AppIcon-1x_U007epad-0-0-0-sRGB-85-220-0.png/460x0w.webp',
        tags: [
            'Kotlin, Java',
            'Retofit',
            'MVP',
            'Dagger',
        ],
        type: 'Supply Chain',
        playstore: 'https://play.google.com/store/apps/details?id=id.co.bri.bristore&hl=en',
        appstore: 'https://apps.apple.com/id/app/bristore/id1491475274',
        github: '',
        gallery: [
            'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/f2/6f/04/f26f0419-d59b-ff63-8137-79ede4028902/dca9cd80-9cd2-425d-833f-640fe50f65e5_resize.jpg/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/43/0a/0f/430a0f91-88dc-7096-ef26-cc1ad84200ec/92e6c7bf-a3e7-4612-8ba8-af57c7d83816_3.PNG/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/00/58/88/00588860-859b-b724-6544-3bb3bdc371d8/3444844f-b17f-4829-bd57-921a950bd131_1242x2688.PNG/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/33/cb/ed/33cbed8f-0c6c-bec8-5975-95451d7e863c/63895682-a7e8-4850-9199-935fa5013004_4.PNG/460x0w.webp'
        ],
    },
    {
        name: 'Em-HR Mobile',
        description: 'Em-HR Mobile is an intelligent Human Resource application designed to streamline and enhance your HR business processes. It offers a wide range of modules, including attendance and visit tracking, leave management, overtime requests, payment requests, medical claims, business trip management, and digital payslips. Additionally, it supports facility management, provides access to company news, product updates, and memos, and facilitates a smooth exit interview process—making it a comprehensive solution for modern HR needs.',
        thumbnail: 'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/70/92/95/709295fa-6fcb-f5db-e754-cd096362691a/AppIcon-0-0-1x_U007emarketing-0-11-0-sRGB-85-220.png/460x0w.webp',
        tags: [
            'Flutter',
            'Riverpod',
            'Dio',
            'Get It',
            'Kotlin Multiplatform (Try another tech just for add skill) =>',
            'Ktor',
            'Coroutines',
            'Koin',
            'Jetpack',
            'Compose',
            'Navigation',
            'SwiftUI / UIKit',
            'GraphQL'
        ],
        type: 'HRIS',
        playstore: 'https://play.google.com/store/apps/details?id=id.co.empore.emhrmobile&pcampaignid=web_share',
        appstore: 'https://apps.apple.com/id/app/em-hr-mobile/id1550924123',
        github: '',
        gallery: [
            'https://play-lh.googleusercontent.com/Eua53LulLBI9fHnR63C3Acz3gtEh0M1i5VyCjA7T27-bk7VHrUk7gc573LRSYR44MqQ=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/q8sHez9yAGDqrE4m3JED5gQznKd7QCsEdgdWw4xSvyTNbEhoE81bGjPvPln4pmCbjvP_=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/9gfTwm_EnZf6TCnLFFQOEBRfPTV04Xp_O9jRlKKw7QrcKE8D5YUBV_R87U1UAx8QWgk=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/kxhx5qT5mEdPgVs-rSlOyfvcI44hGD1t3HFBBifKOdUJebtGKsxRCNX54_WYqX1fkIM=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/zTo4BKzZc9mCzy2HgLZIU_mVyFD68Qk9fPTqAzVncax1NZocbVe4nAoHljeTsFGlDQ=w5120-h2880-rw',
        ],
    },
    {
        name: 'MViCall',
        description: 'MviCall is an innovative and trending mobile app that allows you to display a video of your choice—whether from your gallery, the MviCall Marketplace, or a self-recorded clip—directly on your friend’s phone when you call them. Packed with exciting features like Video Ringtone (Videotone), Video Alarm, customizable status updates, personal contact-based video messages, and a rich video collection, MviCall brings a new level of personalization to your calling experience. Users can also explore trending videos through Live Explore, access exclusive content from creators in the Marketplace, and earn rewards through sharing and engagement. With integration to your phone number and contacts, MviCall ensures a seamless way to stay connected with a personal and entertaining touch.',
        thumbnail: 'https://is1-ssl.mzstatic.com/image/thumb/Purple125/v4/8a/d6/ee/8ad6ee4f-4d17-12ae-7c9d-6f5a667ac607/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/460x0w.webp',
        tags: [
            'Flutter',
            'Dio',
            'Riverpod',
            'Hive',
            'Flutter Secure Storage',
            'Get It',
            'GraphQL'
        ],
        type: 'Video Calls',
        playstore: 'https://play.google.com/store/apps/details?id=com.sbimv.mvicalls&pcampaignid=web_share',
        appstore: 'https://apps.apple.com/id/app/mvicall/id1439159035',
        github: '',
        gallery: [
            'https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/1d/92/1d/1d921d57-1622-aef0-925b-29b98ec13068/9c4b0a0b-fe9e-4a6b-b8f1-2d2b04acfe4b_Frame_169.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/7e/79/98/7e7998b9-07f0-9c88-a84f-c6b48d37cf5e/8670a346-90b3-456f-8438-640fc04b481d_Frame_168.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple124/v4/48/a0/57/48a05731-b1ad-85e2-0a5d-7b1dee75fc7d/76a1f867-cd51-464d-8b82-92bb43526b31_Frame_167.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/Purple114/v4/4c/80/81/4c808164-208d-7fdf-2d2e-91c85a33ef89/29dc498a-3e1d-40d0-b11b-f3c7d8843816_Frame_172.png/460x0w.webp',
            'https://is1-ssl.mzstatic.com/image/thumb/PurpleSource124/v4/38/9f/9e/389f9ec5-5d98-eefc-01f8-12a52a316889/66f9e8cd-4337-4d37-befd-025485bb5e93_7-EN.png/460x0w.webp',
        ],
    },
    {
        name: 'Milov',
        description: 'Milov is a love match game that lets you connect with millions of users through engaging and interactive features. With video profiles, Milov ensures authentic user experiences while helping you explore nearby matches. The unique Scan feature predicts your compatibility and guides you toward your potential soulmate. For safety, chatting is only enabled when both users invite each other, making every connection secure and mutual. Discover real people, real profiles, and real chemistry — all in one app with Milov!',
        thumbnail: 'https://play-lh.googleusercontent.com/e7lPZ7bpmEYOQfRjL9KfB9DKc5Zt9Xiz0XAdqq7D2fwJBkYdNAJbGRxLNvDOjd2BXVI=w480-h960-rw',
        tags: [
            'Flutter',
            'Riverpod',
            'Dio',
            'Get It',
        ],
        type: 'Love Match Game',
        playstore: 'https://play.google.com/store/apps/details?id=com.aman.milov',
        appstore: '',
        github: '',
        gallery: [
            'https://play-lh.googleusercontent.com/atecwMAvjap_R-Hcp_P4JKGY0SHvXapCPlJwSwUkH1Kdz3C-2M5WRCAbao4iFkGdIKI=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/hQss7djk-F03bkCIbwP0IDDkJD68nYMxQ9HZ31BlGPimWNb0ZceKwymT2fZ_tIeiauA=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/AizDJZDpCD__q3LfIENwxtpjZwwB8RM4PjQWqsm-I3YjhwR1mTrkoUH4mBt0XiwCK0c=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/Y0VZNIshBSWcJjlENIC4mcXPIKFPm3a-30MMTDPhFDNmaNCLaxhQIndObEyEYkz8JAs=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/Ix_1Z-t6Tbl1O4N1W52lbrTdu9TfTaCrnv8x7tAZB5jNZzkFloKY7YGjj5pPp0bG5AI=w5120-h2880-rw'
        ],
    },
    {
        name: 'Pantura',
        description: 'Is a special application for Pantura Dangdut Music. In this application, customers can watch Dangdut Pantura videos for free (subject to data/GPRS rates). Customers can also get the opportunity to get attractive REWARDS, Smartphones, Cash of tens of millions of rupiah, Pure Gold of tens of Grams, and Yamaha Nmax Motorbikes by taking the Quiz and answering all questions correctly about Dangdut Pantura Music',
        thumbnail: 'https://i.scdn.co/image/ab67616d0000b2733590c6fe59f111661b1e576e',
        tags: [
            'Kotlin, Java, Swift',
            'Retrofit',
            'Dagger',
            'MVVM',
            'SwifUI / UIKit',
            'Alamofire'
        ],
        type: 'Dangdut Music',
        playstore: 'https://play.google.com/store/apps/details?id=com.iam.dangdutpantura',
        appstore: '',
        github: '',
        gallery: [
            'https://play-lh.googleusercontent.com/4BqaOeDPpTnXx0JpYFIVogmvRvebNEDh32xSpoTaCy4OGlM7nkZ8KHJ7GIKo9x3T2ng=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/IDVVNIxPw2MP6YTAh6hc0RTQC4HVENnlWLvy_fWSHQiWoPwyM-4LddtBKCmr7PBN6w=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/6gaqUjWSLJWFd3WXj0dUnwt0FQTekyPVsLT1-xrT5k8cw854TXwD9CXoR0QOTueB2g=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/HkndkuSeHLv1NBBt3IrFlnPyFEkWkJ7G-2ncrTrFQhMoykcwAiyr2umw6RH16nYQMdw=w5120-h2880-rw'
        ],
    },
    {
        name: 'Ayo Golf',
        description: 'AyoGolf offers a seamless golfing experience with convenient Course Booking, allowing users to reserve their preferred golf courses anytime, anywhere, and even select their preferred caddy. The app also features a Coaching Clinic, where users can watch the latest instructional videos from professional golfers to improve their skills and techniques.',
        thumbnail: 'https://png.pngtree.com/png-clipart/20221028/original/pngtree-golf-tournament-logo-png-image_8736671.png',
        tags: [
            'Flutter',
            'Bloc',
            'GraphQL',
            'Dio',
            'Get It',
        ],
        type: 'Golf Reservation',
        playstore: 'https://play.google.com/store/apps/details?id=app.ayo.golf',
        appstore: '',
        github: '',
        gallery: [
            'https://play-lh.googleusercontent.com/7KMC-y9Z1erR5ggRHqfCPDCm5Hqov1RzwGkz0Eh-HxxhpPOVbWG4PyerBGBQFaGttb8=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/N_aiXuHEQy2GmLzjKF6_PgFWi0R0NWsK_LRuGn1ExVBB755uWREksNpFURheQ3oVQmc=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/48ykAIA1VKIP32jdE5SkjQeLgmvOUsGOiL4ooHlM4zWsU_wKA1PrHB7RFj16lIcbmQ=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/tdT84T65jREFHNW5IeLQdMDU7j-_MyDNFlLt0EWD-Q6MXxWzQELt2uT1qIQuDhRHFLw=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/jmTOZLXlQ__j5p0PVm0wyFTI-B8dOpjwRazkNekeAJkCpoiXCc11aWgugTw74_mTR-w=w5120-h2880-rw'
        ],
    },
    {
        name: 'Carswold',
        description: 'Accurate Information, Faster Car Solutions! Now you can quickly find nearby car services such as workshops, car washes, service bureaus, and gas stations—making all your car-related needs easier and faster to manage, right from your location.',
        thumbnail: 'https://carsworld.co.id/wp-content/themes/carsworld-catalog/img/icons/favicon.png',
        tags: [
            'React Native',
            'Redux',
            'Typescript',
            'Axios',
            'Expo',
        ],
        type: 'Automotive',
        playstore: '',
        appstore: '',
        github: '',
        gallery: [

        ],
    },
    {
        name: 'NF Juara',
        description: 'NF Juara is the most affordable UTBK Tryout application in Indonesia, offering comprehensive online tutoring with a structured curriculum, over 500,000 practice questions, 11,000+ engaging learning videos, and dozens of Super Intensive Tryouts to help students confidently prepare for the 2025 UTBK SNBT and Independent Exams. Key features include high-quality tryouts with accurate scoring systems, real-time SNBP Rationalization to predict your admission chances, Instant Tryouts for quick practice, and a "Consul" feature that allows students to consult directly with experienced NF teachers for better understanding and guidance.',
        thumbnail: 'https://play-lh.googleusercontent.com/hxlZgbFFTODT8Bq-DGRDKCA3lQSiPMZTDr33hbl-_j2uluc_C-e8ZxWLQRdrjbTNbRot',
        tags: [
            'Flutter',
            'Bloc',
            'Dio',
            'Get It',
            'Json Serializable'
        ],
        type: 'Online Course',
        playstore: 'https://play.google.com/store/apps/details?id=id.co.nurulfikri.nfjuara',
        appstore: '',
        github: '',
        gallery: [
            'https://play-lh.googleusercontent.com/lFtSO8DaLpmVR12WfORvgSNs-7rNNKR1jToJeFHg2Io2hY8_0Uoa2CQ-7490WZarmWn2=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/UXDLYZogzS-opDNswH2yT6UZrbEqXU7pK1LrYDSyiYBkaKbsLmH-AQDJTkuHzDwp-Sw=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/IR-Fvamnt_IarbJj-ejCiD1zvgIAjTDvovrxo31zM0x8OjYLOXZjCXL_B4dWDdgDB8MA=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/vjOhlQju8YR9fKzNlQSwTMOyFbGMOfLFoc-bHKs77jAnR-DFEso65aOzF8N5Z82m6g=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/2WXnAes27euctoqf0cOZOBC3ekamGC0NalN37E7KKejhw8GGtyOi82X9lfkbPjns8tw=w5120-h2880-rw',
            'https://play-lh.googleusercontent.com/xidqTZaSOEDcfC4-M_nntW4xyh2UbH0R-lIPzeNrfH0XGFsEBsxeq5oyEL398BcSD46n=w5120-h2880-rw'
        ],
    },
    {
        name: 'Manstore',
        description: 'Manstore is an online shopping application specifically designed for men’s fashion enthusiasts. It offers a curated selection of well-known fashion brands, making it easier for users to discover and purchase trendy and high-quality clothing, footwear, and accessories in one place. With a stylish and user-friendly interface, Manstore provides a seamless shopping experience, complete with secure payments, regular promotions, and fast delivery — catering to the modern mans lifestyle and fashion needs.',
        thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl1E1ycADLM4JSVTdHxIUynYqfHp0Ztt7JYJM4nbqohvWIdva8hNRtz7pBkOBoNgQFxp8&usqp=CAU',
        tags: [
            'Kotlin',
            'Retrofit',
            'Jetpack',
            'Compose',
            'MVVM',
            'Hilt',
            'Coroutines'
        ],
        type: 'Shopping',
        playstore: '',
        appstore: '',
        github: 'https://github.com/FajarSubeki/Manstore',
        gallery: [
            'https://raw.githubusercontent.com/FajarSubeki/Manstore/main/screenshoot/login.png',
            'https://github.com/FajarSubeki/Manstore/raw/main/screenshoot/home.png',
            'https://github.com/FajarSubeki/Manstore/raw/main/screenshoot/profile.png',
            'https://github.com/FajarSubeki/Manstore/raw/main/screenshoot/cart.png',
            'https://github.com/FajarSubeki/Manstore/raw/main/screenshoot/cartdetail.png'
        ],
    },
    {
        name: 'Shopnow',
        description: 'I contributed as a Front-End Developer to this collaborative project for my company. The project involved building a fully responsive multi-vendor e-commerce website. The platform includes a comprehensive range of functionalities, from seamless payment integration to user-friendly navigation and design. My role focused on delivering a smooth, responsive experience across devices while ensuring high performance and accessibility.',
        thumbnail: 'https://t3.ftcdn.net/jpg/14/52/94/36/360_F_1452943661_qI8YC9iT48c19XiWIlohD57PfzT0BqcQ.jpg',
        tags: [
            'Flutter'
        ],
        type: 'Korean Shop',
        playstore: '',
        appstore: '',
        github: 'https://github.com/FajarSubeki/shopnow',
        gallery: [
            'https://raw.githubusercontent.com/FajarSubeki/shopnow/main/assets/screenshoots/ss_1.png',
            'https://github.com/FajarSubeki/shopnow/raw/main/assets/screenshoots/ss_2.png',
            'https://github.com/FajarSubeki/shopnow/raw/main/assets/screenshoots/ss_3.png',
            'https://github.com/FajarSubeki/shopnow/raw/main/assets/screenshoots/ss_4.png'
        ],
    },
    {
        name: 'Removie',
        description: 'I contributed as a Front-End Developer to this collaborative project for my company. The project involved building a fully responsive multi-vendor e-commerce website. The platform includes a comprehensive range of functionalities, from seamless payment integration to user-friendly navigation and design. My role focused on delivering a smooth, responsive experience across devices while ensuring high performance and accessibility.',
        thumbnail: 'https://images.sftcdn.net/images/t_app-icon-m/p/e4826ea5-125c-4f9d-bbb4-a0de81f5a0f0/3363315856/film-app-apk-guia-moviles-logo',
        tags: [
            'React Native',
            'Axios',
            'Expo',
            'Java Script',
            'Native Wind',
        ],
        type: 'Movie',
        playstore: '',
        appstore: '',
        github: 'https://github.com/FajarSubeki/reactmovie',
        gallery: [

        ],
    },
    {
        name: 'Degames',
        description: 'This application is a game catalog platform that provides comprehensive information about video games. Users can browse a list of games, each displaying the game’s name, release date, background image, and Metacritic score. When selecting a game, users are taken to a detailed view that features a banner image, genre tags, full game description, a screenshot carousel slider, supported platforms, developers, and publishers. The app includes a share feature, allowing users to easily share game details with others. To ensure a smooth and organized experience, the game list is equipped with pagination, making it easier to navigate through a large collection of titles.',
        thumbnail: 'https://w7.pngwing.com/pngs/24/817/png-transparent-playstation-4-raiders-of-the-broken-planet-playstation-network-playstation-plus-playstation-electronics-text-trademark.png',
        tags: [
            'Flutter',
            'Bloc',
            'Dio',
            'Get It',
        ],
        type: 'Games',
        playstore: '',
        appstore: '',
        github: 'https://github.com/FajarSubeki/thegames',
        gallery: [
            'https://github.com/FajarSubeki/thegames/raw/main/assets/screenshoot/list_game.png',
            'https://github.com/FajarSubeki/thegames/raw/main/assets/screenshoot/detail_game.png',
            'https://github.com/FajarSubeki/thegames/raw/main/assets/screenshoot/detail_game2.png'
        ],
    },
]